baseURL = 'https://zssv320.github.io/MISAMO-O/'
canonifyurls = true
languageCode = 'zh'
publishDir = "docs"
title = 'MISAMO^O.O^'
theme = 'ananke'
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
