baseURL = 'https://example.org/'
languageCode = 'zh'
publishDir = "docs"
title = 'MISAMO^O.O^'
theme = 'ananke'
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
